create database pizza;
use pizza;
select* from pizza_sales;

select sum(total_price) as Total_Revenue from pizza_sales;

SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID) AS AVG_ORDER_VALUE FROM PIZZA_SALES;

SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES;

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER FROM PIZZA_SALES;
 
SELECT CAST(SUM(QUANTITY) / COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2))
 AS AVG_PIZZA_PER_ORDER FROM PIZZA_SALES;
 #CAST used to convert data into decimal
 
 DESC PIZZA_SALES;
 SELECT STR_TO_DATE('01-01-2015', '%d-%m-%Y');
 SELECT DAYNAME(STR_TO_DATE('01-01-2015', '%d-%m-%Y'));
 SELECT
    order_date,
    DAYNAME(STR_TO_DATE(order_date, '%d-%m-%Y')) AS day_name
FROM pizza_sales;

  
SELECT
    DAYNAME(STR_TO_DATE(ORDER_DATE, '%Y-%m-%d')) AS ORDER_DAY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY DAYNAME(STR_TO_DATE(ORDER_DATE, '%Y-%m-%d'));

SELECT
    HOUR(ORDER_TIME) AS ORDER_HOUR,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY HOUR(ORDER_TIME)
ORDER BY ORDER_HOUR;

SELECT
    MONTHNAME(STR_TO_DATE(ORDER_DATE, '%Y-%m-%d')) AS MONTH_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY MONTHNAME(STR_TO_DATE(ORDER_DATE, '%Y-%m-%d'))
ORDER BY TOTAL_ORDERS DESC;

select* from pizza_sales;

SELECT PIZZA_CATEGORY,
    ROUND(SUM(TOTAL_PRICE) * 100.0 /(SELECT SUM(TOTAL_PRICE)
	FROM PIZZA_SALES
	WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%Y-%m-%d')) = 1),2) AS SALES_PERCENTAGE
FROM PIZZA_SALES
WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%Y-%m-%d')) = 1
GROUP BY PIZZA_CATEGORY
ORDER BY SALES_PERCENTAGE DESC;


select pizza_size,
    sum(total_price) as total_sales,
       cast(sum(total_price)*100/(select sum(total_price) from pizza_sales)  as decimal(10,2)) as sales_percentage
from pizza_sales
group by pizza_size
order by sales_percentage desc;

SELECT
    PIZZA_CATEGORY,
    SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY
ORDER BY TOTAL_PIZZAS_SOLD DESC;

SELECT PIZZA_NAME,
	   SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES
       GROUP BY PIZZA_NAME
       ORDER BY TOTAL_REVENUE DESC
       LIMIT 5;
       
       SELECT PIZZA_NAME,
	   SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES
       GROUP BY PIZZA_NAME
       ORDER BY TOTAL_REVENUE ASC
       LIMIT 5;
       
         
       SELECT PIZZA_NAME,
	    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER FROM PIZZA_SALES
       GROUP BY PIZZA_NAME
       ORDER BY TOTAL_ORDER ASC
       LIMIT 5;
       
       SELECT @@HOSTNAME,@@port;
       select current_user();
       select user();
       alter user 'root@localhost' identified by 'SHREEjyo@760s123';

       
       
       SELECT @@SERVERNAME;
#SHREEjyo@760s123 PASSWORD-ORACLE

select 1;



